/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6740f95a-05db-4f85-95aa-875a02352834",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OGatzCOB7",
    "aws_user_pools_web_client_id": "322cr6lr5796o30t83mlq7juc5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rgqmrb2z7rg5hl7qt3vwte52re.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
