/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:54aa4b77-8667-43db-bda4-7fee3bc32106",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dmvtrqoEu",
    "aws_user_pools_web_client_id": "3hn280k89bj0scplk506k2e0c8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nynmdgcoqncizcwg7vej5lzo3u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
