/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f8ce3c04-a700-408c-b712-0be1fd1a90f4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SikCm2Aeh",
    "aws_user_pools_web_client_id": "33f9vk2j8f3td1pcqki4otuu4s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://raw52mmhcvaf3frmbmfq4mnvly.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
